# Generated by Django 3.1.5 on 2021-02-18 03:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ativos',
            new_name='Ativo',
        ),
    ]
