# Generated by Django 3.1.5 on 2021-02-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_auto_20210218_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='cod_b3',
            field=models.CharField(max_length=5, verbose_name='Código B3'),
        ),
    ]
