# Generated by Django 3.1.5 on 2021-02-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0004_auto_20210225_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='lim_inf',
            field=models.FloatField(verbose_name='Comprar em'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='lim_sup',
            field=models.FloatField(verbose_name='Vender em'),
        ),
    ]
